//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTabel
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string SystemName { get; set; }
        public string IssueType { get; set; }
        public string className { get; set; }
        public string MethodName { get; set; }
        public DateTime DateTime { get; set; }
        public int RequestNumber { get; set; }
        public Nullable<int> RequestName { get; set; }
        public int Status { get; set; }
        public string Comment { get; set; }
        public string error { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModefiedDate { get; set; }
        public Nullable<int> ModefiedBy { get; set; }
    
        public virtual Status Status1 { get; set; }
        public virtual UserInformation UserInformation { get; set; }
    }
}
