//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechOneSanjSecondEntities : DbContext
    {
        public TechOneSanjSecondEntities()
            : base("name=TechOneSanjSecondEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<CompanyTabel> CompanyTabels { get; set; }
        public virtual DbSet<UserInformation> UserInformations { get; set; }

        //public System.Data.Entity.DbSet<BuisnessLogic.DTO.CompanyTableDTO> CompanyTableDTOes { get; set; }
    }
}
